{
 "title": "Assisted Migrations",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "assisted-migration-stage,assisted-migration-production"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Health",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\",service=\"migration-planner-metrics\"}) -0",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "CPU by pod",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (pod),\"pod\",\"pod-$1\",\"pod\", \"migration-planner-(.*)\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory consumption by pod",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"migration-planner-(.*)\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"}) by (pod),\"pod\",\"pod-$1\",\"pod\",\"migration-planner-(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Availability (selected time) ",
   "type": "stat",
   "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"api_server\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"api_server\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Number of requests per second based on response code",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(chi_requests_total{service=\"migration-planner-metrics\",path!~\"/health\",exported_service=\"api_server\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Number of requests per second based on response code",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"api_server\", code!~\"2..\"}[$__rate_interval])) / sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"api_server\"}[$__rate_interval]))",
     "legendFormat": "non 2xx"
    },
    {
     "expr": "sum(rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"api_server\",code=~\"5.0\"}[$__rate_interval])) / sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"api_server\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", exported_service=\"api_server\",code!~\"5..|0\"}[$__rate_interval])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"api_server\", code!~\"5..|0\"}[$__rate_interval])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"api_server\", code!~\"5..|0\"}[$__rate_interval])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Latency (<1s)",
   "type": "stat",
   "description": "The percentage of time that the API responds within 1s.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"api_server\", code!~\"5..|0\",le=\"1000\"}[$__range]))\n/\nsum(increase(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"api_server\", code!~\"5..|0\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Agent API overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Availability (selected time) ",
   "type": "stat",
   "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",code!~\"5..|0\",path!~\"/health\"}[$__range]))\n/\nsum(increase(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"agent_server\",path!~\"/health\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Number of requests per second based on response code",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Number of requests per second based on response code",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\", code!~\"2..\"}[$__rate_interval])) / sum(rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\"}[$__rate_interval]))",
     "legendFormat": "non 2xx"
    },
    {
     "expr": "sum(rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\", code=~\"5..0\"}[$__rate_interval])) / sum(rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Latency (<1s)",
   "type": "stat",
   "description": "The percentage of time that the API responds within 1s.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\",path!~\"/health\",le=\"1000\"}[$__range]))\n/\nsum(increase(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\",path!~\"/health\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Agent metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Agents in up-to-date state",
   "type": "stat",
   "description": "Current number of agents in up-to-date state",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_agent_status_count{state=\"up-to-date\",service=\"migration-planner-metrics\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Agents in gathering-inventory state",
   "type": "stat",
   "description": "Current number of agents in gathering-inventory state",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_agent_status_count{state=\"gathering-initial-inventory\", service=\"migration-planner-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histograme of agents' states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "max by (state) (assisted_migration_agent_status_count{service=\"migration-planner-metrics\", state!=\"\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Agents in waiting-for-credential state",
   "type": "stat",
   "description": "Current number of agents in waiting-for-credential state",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_agent_status_count{state=\"waiting-for-credentials\", service=\"migration-planner-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agents in error state",
   "type": "stat",
   "description": "Current number of agents in error state",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_agent_status_count{state=\"error\", service=\"migration-planner-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Cpu usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption by pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"migration-planner.*\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}