{
 "title": "Assisted Migrations SLOs",
 "time": { "from": "now-28h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "exported_service",
    "query": "api_server,agent_server,image_server"
   }
  ]
 },
 "panels": [
  {
   "title": "${exported_service} API availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "exported_service"
  },
  {
   "title": "${exported_service} Availability",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "SLO Definition\n\nOver a 28-day rolling window, 99% of successful requests (defined as those receiving a non-5xx HTTP response) to ${exported_service} APIs are measured"
   }
  },
  {
   "title": "availability",
   "type": "stat",
   "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\", path!=\"/health\"}[$__range]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path!=\"/health\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability - Error Budget Burn Rate (28d)",
   "type": "timeseries",
   "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\", path!=\"/health\"}[$__range]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path!=\"/health\"}[$__range]))) / (1 - 0.99)",
     "legendFormat": "Error budget burn rate"
    }
   ]
  },
  {
   "title": "Error Budget Exhaustion 99%",
   "type": "gauge",
   "description": "An error budget is the maximum amount errors that a technical system can fail without ",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\", path !=\"/health\"}[$__range]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path !=\"/health\"}[$__range])))\n/\n(1 - 0.99)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2% consumption - Critical Burn Rate Alert (5m & 1h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 5 minutes and last 1 hour remains at 13.44 or greater for at least 5 minutes without restoration.",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\", path!=\"/health\"}[5m]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", path!=\"/health\"}[5m]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 5m"
    },
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\",path!=\"/health\"}[1h]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path!=\"/health\"}[1h]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 1h"
    }
   ]
  },
  {
   "title": "5% consumption - Critical Burn Rate Alert (30m & 6h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 30 minutes and last 6 hours remains at 5.6 or greater for at least 5 minutes without restoration.",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\",path!=\"/health\"}[30m]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path!=\"/health\"}[30m]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 30m"
    },
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\",path!=\"/health\"}[6h]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path!=\"/health\"}[6h]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 6h"
    }
   ]
  },
  {
   "title": "10% consumption - Critical Burn Rate Alert (2h & 1d)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 2 hours and last 1 day remains at 2.8 or greater for at least 15 minutes without restoration.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\",path!=\"/health\"}[2h]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path!=\"/health\"}[2h]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 2h"
    },
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\",path!=\"/health\"}[1d]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path!=\"/health\"}[1d]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 1d"
    }
   ]
  },
  {
   "title": "10% consumption - Critical Burn Rate Alert (6h & 3d)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 6 hours and last 3 days remains at 0.934 or greater for at least 15 minutes without restoration.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\",path!=\"/health\"}[6h]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path!=\"/health\"}[6h]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 6h"
    },
    {
     "expr": "(1 - sum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",code!~\"5..|0\",path!=\"/health\"}[3d]))\n/\nsum(rate(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\",path!=\"/health\"}[3d]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 3d"
    }
   ]
  },
  {
   "title": "${exported_service} API latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "exported_service"
  },
  {
   "title": "${exported_service} Latency",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 34 },
   "options": {
    "content": "SLO Definition\n\nOver a 28-day rolling window, 99% of successful requests (defined as those receiving a non-5xx HTTP response) to ${exported_service}} APIs must complete within 1 second"
   }
  },
  {
   "title": "Latency (< 1s)",
   "type": "stat",
   "description": "Percentage of requests of API server are successful with a latency of < 1000ms",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[$__range]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency burning rate 99%",
   "type": "timeseries",
   "description": "An error budget is the maximum amount errors that a technical system can fail without ",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[$__range]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[$__range])))\n/\n(1 - 0.99)",
     "legendFormat": "Error budget burn rate"
    }
   ]
  },
  {
   "title": "Error Budget Exhaustion 99%",
   "type": "gauge",
   "description": "An error budget is the maximum amount errors that a technical system can fail without ",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[$__range]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[$__range])))\n/\n(1 - 0.99)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical Burn Rate Alert (5m & 1h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 5 minutes and last 1 hour remains at 13.44 or greater for at least 5 minutes without restoration.",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[5m]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[5m]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 5m"
    },
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[1h]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[1h]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 1h"
    }
   ]
  },
  {
   "title": "Critical Burn Rate Alert (2h & 1d)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 2 hours and last 1 day remains at 2.8 or greater for at least 15 minutes without restoration.",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[2h]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[2h]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 2h"
    },
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[1d]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[1d]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 1d"
    }
   ]
  },
  {
   "title": "Critical Burn Rate Alert (6h & 3h)",
   "type": "timeseries",
   "description": "Send a warning notification if the burn rate over the last 6 hours and last 3 days remains at 0.934 or greater for at least 15 minutes without restoration.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[6h]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[6h]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 6h"
    },
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[3d]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[3d]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 3d"
    }
   ]
  },
  {
   "title": "Critical Burn Rate Alert (30m & 6h)",
   "type": "timeseries",
   "description": "Page if the burn rate over the last 30 minutes and last 6 hours remains at 5.6 or greater for at least 5 minutes without restoration.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[30m]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[30m]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 30m"
    },
    {
     "expr": "(1 - sum(rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\",le=\"1000\"}[6h]))\n/\nsum(rate(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\",exported_service=\"${exported_service}\", code!~\"5..|0\"}[6h]))) / (1 - 0.99)",
     "legendFormat": "Burn Rate - 6h"
    }
   ]
  }
 ]
}